### ISSUE TITLE
No need to wait for Wire.available().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit-TPA2016-Library#2]
This code "while(!Wire.available());" is not correct.
After Wire.requestFrom() the I2C transmissions has completely finished. The Wire.available() returns the number of bytes in the buffer.

Using the return value of Wire.requestFrom() or testing Wire.available() just once can be done to detect a problem with the sensor (when it did not give enough data) or a problem with the I2C bus (for example in a multi-Master bus).

**Comment by hoffmannjan** [comment]
fix is in master now, thanks 👍
