### ISSUE TITLE
getGain()

### ISSUE THREAD

**Issue by Yoshi20** [adafruit/Adafruit-TPA2016-Library#3]
The getGain()-function seems to not handle signed values, since the gain in the AGC Fixed Gain Control register (datasheet page 27) returns bit 7 and 6 always as 0.

Here's how I fixed this problem:

```
// for querying the gain, returns in dB
int8_t Adafruit_TPA2016::getGain(void) {
  int8_t gain = int8_t(read8(TPA2016_GAIN));
  gain = gain << 2;
  if ((gain & 0x80) > 0) gain = (gain >> 2) | 0xC0;   // it's a negative value
  else gain = gain >> 2;                              // it's a positive value
  return gain;
}
```

**Comment by querry43** [comment]
This is still a problem and I don't believe it's specific to getGain.  I think the negative gain sent to setGain gets 2's complemented as 8 bits which is incorrect for a 6 bit value.

**Comment by ladyada** [comment]
@hoffmannjan take a look please and fix if needed!

**Comment by hoffmannjan** [comment]
yeah, thanks @Yoshi20, added your fix and now read are correct 👍
