### ISSUE TITLE
wiringPi version for Rapsberry Pi (new branch pull request)

### ISSUE THREAD

**Issue by romibi** [adafruit/Adafruit-TPA2016-Library#4]
I wanted to control the TPA2016 from my Raspberry Pi

Therefore I modified this library for usage with wiringPi

You might want to copy my [wiringPiVersion](https://github.com/romibi/Adafruit-TPA2016-Library/tree/wiringPiVersion) branch to your repository and link it in the readme so that others can find it.

Also see my [speakercontrol](https://github.com/romibi/Adafruit-TPA2016-Speakercontrol) project where I used it.

**Comment by ladyada** [comment]
thank you! we will be writing a circuitpython (Python3) driver for it as well :)

made an issue here: https://github.com/adafruit/circuitpython/issues/1621
